### PR TITLE
SNES Controller Input Support

### PR DESCRIPTION
**Pull request by RobertDaleSmith**
Implements my expanded SNESpad lib as a GP2040 add-on.

Supports standard NES and SNES controllers, as well as the Super Nintendo mouse (movement mapped to analog).

### CODE REVIEW

**Comment by RobertDaleSmith** [comment]
Hey, @FeralAI && @arntsonl I can send y'all an adapter to test SNES input if needed to verify this PR.

**Comment by arntsonl** [comment]
Are you in the Discord? I'm happy to throw some Paypal your way for the adapters to test.

Also we're going to merge this in, just been delayed with the 0.7.1 release today :)

**Comment by donly** [comment]
Thank you @RobertDaleSmith. How to use this add-on to my SNES game console please?

**Comment by RobertDaleSmith** [comment]
> Thank you @RobertDaleSmith. How to use this add-on to my SNES game console please?

This is for reading SNES controllers into GP2040-CE. Not for GP2040-CE to work on SNES consoles. But that I could possibly write an add-on for something like that in the future.

**Review by arntsonl — APPROVED** [review]
Super clean, thank you for the submission and providing an adapter to test!

**Comment by sar320** [comment]
Does this work with hotkey shortcuts? For example, can I set Select + L on the snes controller to function as L2 in xinput mode via the web configurator? Or, would the hotkey combination inputs still have to correspond physically to the gpio pins?

**Comment by supperbentobox** [comment]
I've installed the  GP2040-CE_0.7.10_RP2040AdvancedBreakoutBoardUSBPassthrough.uf2, but after configuring the SNES GPIO and connect it it won't function or let you use the web config MODE

Any clear indication where to look detailed information on how to connect the SNES controller and how to configure it correctly?

I wanted to use it with consoles and PC, i use a non standar configuration with Start button as L2, Select as Start and Start + Select as Home button.

Thanks

**Pull request merged**
