### PR TITLE
Recent updates to the custom LED theme page include enhanced color pi…

### PR DESCRIPTION
**Pull request by KeyOnTech**
Updates to the custom LED theme page include enhanced color picker placement options (top, bottom, left, or right) to ensure it never appears off-screen and remains accessible. Additionally, new button layouts for Haute42 (13 & 16 buttons) and DuelPad (16 buttons) have been added to the preview layout options dropdown list.

updates made to the custom led theme page
users can now select where the color picker will appear top, bottom, left, or right preventing picker appearing off screen and unusable
updates made to the preview layout options drop down list
added Haute42 13 & 16 button layouts
added DuelPad 16 button layout

### CODE REVIEW

**Comment by KeyOnTech** [comment]
I have another push coming with some minor updates
I tested on 
Safari
Chrome
MS Edge
Brave
Firefox
Arc

1. I made the size 450px on push
- I did some tightening up and made it closer to the original 400px its now at 425px

3. There is an issue on the Haute42 13 layout, if you shrink the screen to narrow the A2 and A1 buttons slightly overlap
- I spaced the A1 button a little more to the right to fix it

new push on the way

**Comment by FeralAI** [comment]
Hey @KeyOnTech, thanks for the PR! We appreciate the effort to make things easier while we're reworking the LED system.

I've taken a look through the code and tested it out, and here are my notes.

**Rename layouts to match existing layouts in the Display Configuration page**
* `Stickless 13 A` to `Stickless 13`
* `Stickless 16 A` to `Stickless 16`
* `Stickless 16 B` to `Stickless 16A` (TBD, but let's go with this for now)

That last 16 button layout doesn't exist in the Display Configuration currently, so we may want to add that. Probably not a blocker for this PR, but something I'll need to follow up on.

**Using the gradient feature on the new layouts doesn't quite work**
 
image

This is because the matrices for the new layouts in `Buttons.js` are incorrect. These will need to be updated. For example, the `Stickless 16` layout should be:

```
export const STICKLESS_16_A_LAYOUT = [
	[null, 'Left', null, null],
	['A1', 'Down', null, null],
	[null, 'Right', null, 'L3'],
	['A2', 'B3', 'B1', 'Up'],
	[null, 'B4', 'B2', 'R3'],
	[null, 'R1', 'R2', null],
	[null, 'L1', 'L2', null],
];
```
Which will produce: 
image

**Consolidate button arrays into `BUTTTON_LAYOUTS` objects**

I think the button arrays should be rolled into the `BUTTON_LAYOUTS` objects, into properites named `mainButtons` and `auxButtons`. Then [this section](https://github.com/OpenStickCommunity/GP2040-CE/pull/978/files#diff-6223122c7be4370d3812a65a5e2dec8f641514d5e340bdb52313424355db517bR331-R359) can be removed, and instead bind directly against `BUTTON_LAYOUTS[ledLayout].mainButtons` [here](https://github.com/OpenStickCommunity/GP2040-CE/pull/978/files#diff-6223122c7be4370d3812a65a5e2dec8f641514d5e340bdb52313424355db517bR490) or `BUTTON_LAYOUTS[ledLayout].auxButtons` [here](https://github.com/OpenStickCommunity/GP2040-CE/pull/978/files#diff-6223122c7be4370d3812a65a5e2dec8f641514d5e340bdb52313424355db517bR475).

**Color Picker Placement**

This feature works fine and I don't see a problem including it.

**Comment by KeyOnTech** [comment]
Hey sorry for the delay on replying 
I'm just seeing your Github messages for updates I need to make to the the code. Still learning the PR Github features lol
Some I already made others I need to review thanks
I'll go through your notes and make some updates
thanks

**Comment by KeyOnTech** [comment]
gradient button selector not working fixed, moving to next issue

**Comment by KeyOnTech** [comment]
Fixed: Rename layouts to match existing layouts in the Display Configuration page
Fixed: Using the gradient feature on the new layouts doesn't quite work
Fixed: Consolidate button arrays into BUTTTON_LAYOUTS objects

**Comment by KeyOnTech** [comment]
_**That last 16 button layout doesn't exist in the Display Configuration currently, so we may want to add that. Probably not a blocker for this PR, but something I'll need to follow up on.**_

i started to add this part.  I made everything alphabetical and added the 16 A. Its looks like its just 2 drop down lists but I dont know where these values get saved.  If the new values will affect the rest of the application when they get saved and how this will affect the rest of the project.

I did not push this code not sure if you wanted to keep this.

`
const BUTTON_LAYOUTS = [
    { label: 'Beatmania 5 Key Left', value: 0 }, // BUTTON_LAYOUT_BM_5KEY_A
    { label: 'Beatmania 7 Key Left', value: 1 }, // BUTTON_LAYOUT_BM_7KEY_A
    { label: 'Beatmania Turntable Left', value: 2 }, // BUTTON_LAYOUT_BM_TURNTABLE_A
    { label: 'Blank', value: 3 }, // BUTTON_LAYOUT_BLANKA
    { label: 'Board Defined', value: 4 }, // BUTTON_LAYOUT_BOARD_DEFINED_A
    { label: 'Buttons Angled', value: 5 }, // BUTTON_LAYOUT_BUTTONS_ANGLED
    { label: 'Buttons Basic', value: 6 }, // BUTTON_LAYOUT_BUTTONS_BASIC
    { label: 'Custom', value: 7 }, // BUTTON_LAYOUT_CUSTOM
    { label: 'Dancepad', value: 8 }, // BUTTON_LAYOUT_DANCEPADA
    { label: 'DDR Dancepad Left', value: 9 }, // BUTTON_LAYOUT_DANCEPAD_DDR_LEFT
    { label: 'DDR Dancepad Solo', value: 10 }, // BUTTON_LAYOUT_DANCEPAD_DDR_SOLO
    { label: 'Fightboard', value: 11 }, // BUTTON_LAYOUT_FIGHTBOARD_STICK
    { label: 'Fightboard Mirrored', value: 12 }, // BUTTON_LAYOUT_FIGHTBOARD_MIRRORED
    { label: 'Gitadora Fret', value: 13 }, // BUTTON_LAYOUT_GITADORA_FRET_A
    { label: 'Gitadora Strum', value: 14 }, // BUTTON_LAYOUT_GITADORA_STRUM_A
    { label: 'Keyboard', value: 15 }, // BUTTON_LAYOUT_KEYBOARDA
    { label: 'Keyboard Angled', value: 16 }, // BUTTON_LAYOUT_KEYBOARD_ANGLED
    { label: 'Open_Core0 WASD', value: 17 }, // BUTTON_LAYOUT_OPENCORE0WASDA
    { label: 'PIU Dancepad Left', value: 18 }, // BUTTON_LAYOUT_DANCEPAD_PIU_LEFT
    { label: 'Popn Left', value: 19 }, // BUTTON_LAYOUT_POPN_A
    { label: 'Stick', value: 20 }, // BUTTON_LAYOUT_STICK
    { label: 'Stickless', value: 21 }, // BUTTON_LAYOUT_STICKLESS
    { label: 'Stickless 13', value: 22 }, // BUTTON_LAYOUT_STICKLESS_13
    { label: 'Stickless 14', value: 23 }, // BUTTON_LAYOUT_STICKLESS_14
    { label: 'Stickless 16', value: 24 }, // BUTTON_LAYOUT_STICKLESS_16
    { label: 'Stickless 16 A', value: 25 }, // BUTTON_LAYOUT_STICKLESS_16_A
    { label: 'Taiko', value: 26 }, // BUTTON_LAYOUT_TAIKO_A
    { label: 'Twinstick', value: 27 }, // BUTTON_LAYOUT_TWINSTICKA
    { label: 'VLX', value: 28 }, // BUTTON_LAYOUT_VLXA
];

const BUTTON_LAYOUTS_RIGHT = [
    { label: 'Arcade', value: 0 }, // BUTTON_LAYOUT_ARCADE
    { label: 'Beatmania 5 Key Right', value: 1 }, // BUTTON_LAYOUT_BM_5KEY_B
    { label: 'Beatmania 7 Key Right', value: 2 }, // BUTTON_LAYOUT_BM_7KEY_B
    { label: 'Beatmania Turntable Right', value: 3 }, // BUTTON_LAYOUT_BM_TURNTABLE_B
    { label: 'Blank', value: 4 }, // BUTTON_LAYOUT_BLANKB
    { label: 'Board Defined', value: 5 }, // BUTTON_LAYOUT_BOARD_DEFINED_B
    { label: 'Buttons Angled', value: 6 }, // BUTTON_LAYOUT_BUTTONS_ANGLEDB
    { label: 'Capcom', value: 7 }, // BUTTON_LAYOUT_CAPCOM
    { label: 'Capcom 6', value: 8 }, // BUTTON_LAYOUT_CAPCOM6
    { label: 'Custom', value: 9 }, // BUTTON_LAYOUT_CUSTOM
    { label: 'DDR Dancepad Right', value: 10 }, // BUTTON_LAYOUT_DANCEPAD_DDR_RIGHT
    { label: 'Dancepad', value: 11 }, // BUTTON_LAYOUT_DANCEPADB
    { label: 'Fightboard', value: 12 }, // BUTTON_LAYOUT_FIGHTBOARD
    { label: 'Fightboard Mirrored', value: 13 }, // BUTTON_LAYOUT_FIGHTBOARD_STICK_MIRRORED
    { label: 'Gitadora Fret', value: 14 }, // BUTTON_LAYOUT_GITADORA_FRET_B
    { label: 'Gitadora Strum', value: 15 }, // BUTTON_LAYOUT_GITADORA_STRUM_B
    { label: 'Keyboard', value: 16 }, // BUTTON_LAYOUT_KEYBOARDB
    { label: 'Keyboard 8', value: 17 }, // BUTTON_LAYOUT_KEYBOARD8B
    { label: 'Noir 8', value: 18 }, // BUTTON_LAYOUT_NOIR8
    { label: 'Open_Core0 WASD', value: 19 }, // BUTTON_LAYOUT_OPENCORE0WASDB
    { label: 'PIU Dancepad Right', value: 20 }, // BUTTON_LAYOUT_DANCEPAD_PIU_RIGHT
    { label: 'Popn Right', value: 21 }, // BUTTON_LAYOUT_POPN_B
    { label: 'Sega 2P', value: 22 }, // BUTTON_LAYOUT_SEGA2P
    { label: 'Stickless', value: 23 }, // BUTTON_LAYOUT_STICKLESSB
    { label: 'Stickless 13', value: 24 }, // BUTTON_LAYOUT_STICKLESS_13B
    { label: 'Stickless 14', value: 25 }, // BUTTON_LAYOUT_STICKLESS_14B
    { label: 'Stickless 16', value: 26 }, // BUTTON_LAYOUT_STICKLESS_16B
    { label: 'Stickless 16 A', value: 27 }, // BUTTON_LAYOUT_STICKLESS_16B_A
    { label: 'Taiko', value: 28 }, // BUTTON_LAYOUT_TAIKO_B
    { label: 'Twinstick', value: 29 }, // BUTTON_LAYOUT_TWINSTICKB
    { label: 'Viewlix', value: 30 }, // BUTTON_LAYOUT_VEWLIX
    { label: 'Viewlix 7', value: 31 } // BUTTON_LAYOUT_VEWLIX7
];

`

**Comment by KeyOnTech** [comment]
I see a file conflict on the package-lock.json file
I didnt make any updates to any of that I just did a npm i
so hopefully this is a common minor thing
besides that no other conflicts in my latest push 
thanks

**Comment by KeyOnTech** [comment]
Hey @feralai wanted to check in on the updates I made to the color picker screen button layouts and color picker box.  I got a comment today and they were experiencing what I was on different browsers I think my minor updates will help.
wanted to check in and see if my web config updates were good to go and hopefully get approved to make the next build. I think it'll really help folks
Thanks

IMG_3021

**Comment by arntsonl** [comment]
I'll jump in on this one and put in my approval. I like the updates.

**Review by arntsonl — APPROVED** [review]
Looks great! All changes were accounted for and the formatting matches our current web config

**Pull request merged**
