### PR TITLE
Add ergoSHIFT Rev.2 config file

### PR DESCRIPTION
**Pull request by mizma**
Add config file for the [ergoSHIFT Rev.2](https://github.com/mizma/ergoSHIFT/tree/main/hardware-rev2) open-source stick-less controller.

### CODE REVIEW

**Comment by mizma** [comment]
Seems like workflow is not working for ergoSHIFTRev2?

**Comment by TheTrainGoes** [comment]
Hi @mizma , thank you for the PR on this.

My general feedback from looking at your repo:
1 - There are parts of the repo listed as `design not verified`.  This has traditionally lead to issues as people may make boards that could have issues.  For this we would want to wait until the design is solidified, tested and ready for anyone to pickup and make.
2 - It requires the use of JFA SBM parts (keycaps and aux keys).  Ideally there would be a 3D printed alternative to this.  SBM parts can be quite expensive to get in some places.
3 - General concerns around this line `You may need to adjust the rotation, placement of some parts in CPL, check before you order. It should look like the following.`.  If the CPL files are not lining up for services like JLC it will need to be fixed.  This will lead to people not getting working boards or boards that could be missing parts.

Once these main concerns are addressed we can take a look at including the board.  We have an expectation that you will be active in the community if included and offer support for people that have questions about it.

**Review by TheTrainGoes — CHANGES_REQUESTED** [review]
My general feedback from looking at your repo:
1 - There are parts of the repo listed as design not verified. This has traditionally lead to issues as people may make boards that could have issues. For this we would want to wait until the design is solidified, tested and ready for anyone to pickup and make.
2 - It requires the use of JFA SBM parts (keycaps and aux keys). Ideally there would be a 3D printed alternative to this. SBM parts can be quite expensive to get in some places.
3 - General concerns around this line You may need to adjust the rotation, placement of some parts in CPL, check before you order. It should look like the following.. If the CPL files are not lining up for services like JLC it will need to be fixed. This will lead to people not getting working boards or boards that could be missing parts.

Once these main concerns are addressed we can take a look at including the board. We have an expectation that you will be active in the community if included and offer support for people that have questions about it.

**Comment by TheTrainGoes** [comment]
Chatted on Discord - going to close this for now and @mizma will resubmit when these things are worked out.

**Pull request closed without merging**
