### PR TITLE
New Add-On: Rotate Input + Tilt Input = Analog Modification Input

### PR DESCRIPTION
**Pull request by jack2game**
Edit: Hide the old post
<details>
  <summary>Old post</summary>
## Rotate Input

* `Rotate 1 Pin` - The GPIO pin used for the Rotate 1 (Clockwise Rotation).
* `Rotate 1 Degree for Left Stick`
* `Rotate 1 Degree for Right Stick`
* `Rotate 2 Pin` - The GPIO pin used for the Rotate 2 (Counter Clockwise Rotation).
* `Rotate 2 Degree for Left Stick`
* `Rotate 2 Degree for Right Stick`
* `Rotate SOCD Mode` - Choose the default SOCD Cleaning Mode (Neutral, Last Win, Up Priority). 

The Rotate feature in this add-on allows users to control analog stick values on both Left and Right Analogs.

Rotate 1 and Rotate 2 buttons, when pressed with directional buttons, adjust the analog values, with Rotate 1 makes your sticks rotate clockwise and Rotate 2 makes them rotate counter clockwise.

The angle can be adjusted in the web configurator. If you set the rotation angle to be 180, you will effectively swap your Up&Down and Left&Right for your sticks.

Additionally, pressing Rotate 1 and Rotate 2 simultaneously allows the Right stick to function as the D-Pad directions.
</details>

### CODE REVIEW

**Comment by jack2game** [comment]
I want to add that Rotate feature only works when DPad mode is either acting as L Stick or R Stick.

If DPad is set to function as a DPad, the rotation add on will have no impact, as expected.

**Comment by mikepparks** [comment]
Could you possibly elaborate on use cases for this? Seems like this would be better covered by the Analog addon that already exists with improvements to Invert options.

**Comment by jack2game** [comment]
> Could you possibly elaborate on use cases for this? Seems like this would be better covered by the Analog addon that already exists with improvements to Invert options.

Not really. Actually far from that.
1. Analog addon requires additional ADC input, taking 4 extra pins only at 26, 27, 28, 29. It is possible to add rotation (and 2 more buttons) to Analog addon too, but probably much less meaningful. Rotate addon works with all pins and only need 1 or 2 extra buttons. Plus Analog addon doesn't give you precise and consistent angle input like Rotate addon, given Rotate doesn't require ADC inputs. They are very different and for different purposes.
2. Rotate addon allows you to have 360 different possibilities. Invert is only one of them when you set the angle as 180.
3. One typical use would be set Rotate 1 Degree to be 15, and Rotate 2 Degree to be 15, which gives you a total of 24 angles, with only 2 extra pins. A simple illustration can be found below. I only drew the possibilities when using Rotation 1&2 together with Up and Right buttons, but it will work with all diagonals.
4. Rotate
5. This is extremely useful for CastleVania games such as Bloodstaind, which requires both motion inputs and more granularity on angle inputs for right stick when aiming. With Rotate add-on, and DPad mode as default, I only need 3 buttons to achieve 24 angle inputs on Right Stick: Rotate1, Rotate2, and Another button in Slider Addon which changes DPad mode to Right Stick when holding.

Reference:
- Bloodstaind Motion Inputs: [Link](https://steamuserimages-a.akamaihd.net/ugc/789735990649317559/13778275B10CF8A9E306B31A9DA9113AD6E6E7B0/)
- Bloodstaind Control Scheme (requiring Right Stick for aiming): [Link](https://gamefaqs.gamespot.com/a/faqs/87/77487-62.jpg)

**Comment by jack2game** [comment]
## Analog Modification Input

GP2040-CE Configuration - Add-Ons Tilt Input

* `Tilt 1 Pin` - The GPIO pin used for the Tilt 1 direction.
* `Tilt 2 Pin` - The GPIO pin used for the Tilt 2 direction.
* `Rotate 1 Pin` - The GPIO pin used for the Rotate 1 (Clockwise Rotation).
* `Rotate 2 Pin` - The GPIO pin used for the Rotate 2 (Counter Clockwise Rotation).
* `Tilt 1 X-Axis Factor for Left Stick`
* `Tilt 1 Y-Axis Factor for Left Stick`
* `Tilt 1 X-Axis Factor for Right Stick`
* `Tilt 1 Y-Axis Factor for Right Stick`
* `Tilt 2 X-Axis Factor for Left Stick`
* `Tilt 2 Y-Axis Factor for Left Stick`
* `Tilt 2 X-Axis Factor for Right Stick`
* `Tilt 2 Y-Axis Factor for Right Stick`
* `Rotate 1 Degree for Left Stick`
* `Rotate 1 Degree for Right Stick`
* `Rotate 2 Degree for Left Stick`
* `Rotate 2 Degree for Right Stick`
* `Analog Modification Left Analog Up Pin` - The GPIO pin used for the Up direction on the Left analog stick.
* `Analog Modification Left Analog Down Pin` - The GPIO pin used for the Down direction on the Left analog stick.
* `Analog Modification Left Analog Left Pin` - The GPIO pin used for the Left direction on the Left analog stick.
* `Analog Modification Left Analog Right Pin` - The GPIO pin used for the Right direction on the Left analog stick.
* `Analog Modification Right Analog Up Pin` - The GPIO pin used for the Up direction on the Right analog stick.
* `Analog Modification Right Analog Down Pin` - The GPIO pin used for the Down direction on the Right analog stick.
* `Analog Modification Right Analog Left Pin` - The GPIO pin used for the Left direction on the Right analog stick.
* `Analog Modification Right Analog Right Pin` - The GPIO pin used for the Right direction on the Right analog stick.
* `Analog Modification SOCD Mode` - Choose the default SOCD Cleaning Mode (Neutral, Last Win, Up Priority). 

The Tilt feature in this add-on allows users to control analog stick values on both Left and Right Analogs.
* Tilt 1 and Tilt 2 buttons, when pressed with directional buttons, adjust the analog values.
* Default settings tilt the Left stick at 65% for Tilt 1 and 35% for Tilt 2.
* The Right stick shifts down for Tilt 1 and up for Tilt 2 by default.
* Additionally, pressing Tilt 1 and Tilt 2 simultaneously allows the Right stick to function as the D-Pad directions.

The Rotate feature in this add-on allows users to control analog stick values on both Left and Right Analogs.
* Rotate 1 and Rotate 2 buttons, when pressed with directional buttons, adjust the analog values, with Rotate 1 makes your sticks rotate clockwise and Rotate 2 makes them rotate counter clockwise.
* The angle can be adjusted in the web configurator. If you set the rotation angle to be 180, you will effectively swap your Up&Down and Left&Right for your sticks.
* Additionally, pressing Rotate 1 and Rotate 2 simultaneously allows the Right stick to function as the D-Pad directions.

**Comment by InfraredAces** [comment]
### Function

Loading [this build](https://github.com/OpenStickCommunity/GP2040-CE/actions/runs/6555558737) onto an existing configured device, I encountered some flickering inputs that were were slightly tilted. This issue only went away with doing a complete reset from the webconfig or by flashnuking the device.

Gif of Issue

Additionally, both LS and RS default to Neutral SOCD cleaning regardless of the setting in webconfig.

### Documentation

> docs/add-ons/analogmod.md
> * `Rotate 1 Degree for Left Stick`
> * `Rotate 1 Degree for Right Stick`
> * `Rotate 2 Degree for Left Stick`
> * `Rotate 2 Degree for Right Stick`

For the documentation, please be as verbose as possible. It should be apparent from looking at the documentation what each of the options should do, as users may not be able to tell just from looking at the  and what values are permissible. Is there a range of acceptable values or is any value (100000, -20, etc)?

For the documentation, please update the images so that users can view what the menu should look like.

**Comment by mikepparks** [comment]
So far, my biggest concern with all of this is the unrequested changing of names on things that do not need to be changed just to make the desired adjustments.  It muddies the waters for the sake of semantics.  I see more commits here that change what exists in name only than I do things that actually improve or modify functionality.  My advice would be to step back, reincorporate your actual changes from this PR into the existing addon as a new PR, and leave the structural and semantic concepts for the team to decide.

**Comment by jack2game** [comment]
Updated proto in commit https://github.com/OpenStickCommunity/GP2040-CE/pull/558/commits/3dbb341ad97442e37dc34c0d109ab5f13b70b838. Just want to note that following fields are left untouched but no longer used.
<details>
  <summary>Legacy pronto fields</summary>
optional int32 tiltFunctionPin = 4;<br>
optional int32 tiltLeftAnalogUpPin = 5;<br>
optional int32 tiltLeftAnalogDownPin = 6;<br>
optional int32 tiltLeftAnalogLeftPin = 7;<br>
optional int32 tiltLeftAnalogRightPin = 8;<br>
optional int32 tiltRightAnalogUpPin = 9;<br>
optional int32 tiltRightAnalogDownPin = 10;<br>
optional int32 tiltRightAnalogLeftPin = 11;<br>
optional int32 tiltRightAnalogRightPin = 12;<br>
optional SOCDMode tiltSOCDMode = 13;<br>
</details>

**Comment by arntsonl** [comment]
Let me first say thank you for adding onto the tilt add-on! After some thought, I'm going to close this PR and have you submit a new one with just the rotation changes with the following requests:

1. Change analogmod.* back to tilt.*, we've established this as the tilt add-on and do not want to change the meaning of tilt
2. Change all of the renames in protobuf back to tilt* nomenclature.
3. Resubmit the PR once the files and naming has been changed back to tilt, that way it should be WAY less code and much easier to track in github.

**Pull request closed without merging**
