### PR TITLE
Flatbox ver SZ firmware

### PR DESCRIPTION
**Pull request by shinzero96**
Hi team. I'm a maker based in Vietnam and I wish to have my firmware updated with the official release so it will be easier for my customer to find the firmware. Thank you so much!

### CODE REVIEW

**Comment by TheTrainGoes** [comment]
Hi @shinzero96,

Is this an open source design?

**Comment by shinzero96** [comment]
hi @TheTrainGoes 
Sure, this is just a Pico Pi slap on an extension board. Do I have to upload my board design, and where do I upload it?

**Comment by TheTrainGoes** [comment]
Hi @shinzero96 ,

I looked over the files as well as your FaceBook page for the company.   

We do not include commercial devices unless there is strong demand for them from the public.   

I would recommend that you make a fork of the project so that you can offer the releases directly to your customers.  

If we start seeing significant demand for the firmware in our Discord then we can re-evaluate including it in our main release section.  

Thank you.

**Comment by shinzero96** [comment]
@TheTrainGoes Thank you for taking your time sir.

**Pull request closed without merging**
