### PR TITLE
Added new stickless 14 button display option

### PR DESCRIPTION
**Pull request by jnkhac**
Changes:
Added a new stickless 14 button layout to resemble my Fightingbox Flatbox Ultra layout.

Without input history:

With input history:

Issues:
1. Currently in the web configurator, under Configuration => Display Configuration, when setting either of the button layouts to "Custom", "Stickless 14" does not appear under the drop down menu of the "Custom Button Layout Params".
2. My device is unsupported and the layout is not that common. There are other devices with similar layouts such as the Chocobox Beastbox and the TSR:ACT HyperCube but they are also not supported and don't have a screen.

Questions:
1. My device is unsupported so I know its config file will never be on the official repo, and a compatible config file is not that accessible. Is there a place where I can upload my uf2 file for the device for more people to see? For now I'm looking into uploading it to github as a release on my fork.

### CODE REVIEW

**Comment by TheTrainGoes** [comment]
Hi @jnkhac ,

Are you the original creator of the Flatbox Ultra?

**Comment by jnkhac** [comment]
@TheTrainGoes I am not the original creator. I just own one.

**Comment by TheTrainGoes** [comment]
@jnkhac I have been on the fence about this one (not your code).

Are you on our Discord?  If so can you toss me a DM to chat?

**Comment by jnkhac** [comment]
@TheTrainGoes Yes I'm in the discord. I've sent you a DM.

**Review by TheTrainGoes — CHANGES_REQUESTED** [review]
With the #825 merge this will need a very small update and then we can merge it.

**Review by TheTrainGoes — APPROVED** [review]

**Pull request merged**
