### PR TITLE
Another 4-Way Joystick Mode implementation

### PR DESCRIPTION
**Pull request by sirrow**
This is quick implementation which meet my expectation described in https://github.com/OpenStickCommunity/GP2040-CE/issues/532.

### CODE REVIEW

**Comment by TheTrainGoes** [comment]
Hi @sirrow ,

I will check thit out when I have some time

**Comment by bsstephan** [comment]
@sirrow is it the case that the draft only addresses Scenario 2? I don't have a great way to test SOCD=Off at the moment, but it appears that Scenario 1's behavior is the same with your draft.

**Comment by sirrow** [comment]
> @sirrow is it the case that the draft only addresses Scenario 2? I don't have a great way to test SOCD=Off at the moment, but it appears that Scenario 1's behavior is the same with your draft.

As you @bsstephan described at https://github.com/OpenStickCommunity/GP2040-CE/issues/532#issuecomment-1728300593, conbination of  https://github.com/OpenStickCommunity/GP2040-CE/pull/533 and https://github.com/OpenStickCommunity/GP2040-CE/pull/537 works well.

**Comment by sirrow** [comment]
https://github.com/OpenStickCommunity/GP2040-CE/pull/537 is already merged.
I make this ready for review with current implementation.

I'll write another pull request for revise the implementation for ease of understand, rewrite with std::list.

**Comment by sirrow** [comment]
I revised my implementation with std::list.
New implementation is functionally same as previous one.

Old implementation is moved to https://github.com/sirrow/GP2040-CE/tree/4way-alt-implementation-dev-v1

**Review by arntsonl — APPROVED** [review]
Looks good, standard list makes sense if we're doing push/pop.

**Pull request merged**
