### PR TITLE
Add Flatbox Rev5 RGB

### PR DESCRIPTION
**Pull request by SavageCore**
Test build: https://github.com/OpenStickCommunity/GP2040-CE/suites/14156305162/artifacts/793156062

### CODE REVIEW

**Comment by SavageCore** [comment]
I assume this works fine for v2 and the user will just need to set LEDs per button to 2?

**Comment by TheTrainGoes** [comment]
That's correct.  Rev1 would also need the PLED numbers changed on it.  

V1 is depreciated now so I'm fine just hosting v2.

**Comment by SavageCore** [comment]
@TheTrainGoes OK makes sense. Updated to 2 LEDs per button, PLED pins are 12-15, is that right?

**Comment by TheTrainGoes** [comment]
PLED pins are 24, 25, 26 and 27

**Comment by TheTrainGoes** [comment]
Correction - LED # not PIN number.

**Review by TheTrainGoes — APPROVED** [review]

**Pull request merged**
