### PR TITLE
Fix keyboard host mapping

### PR DESCRIPTION
**Pull request by deeebug**
This should address #395.
Thanks to @InfraredAces for thorough testing and a very descriptive writeup about the issue!

The fix is very simple and a mistake from my side, sorry for that.
Edit: The addon has been enabled for testing purpose. It can be disabled if there are difficulties in making the merge.

Please check and merge, thanks!

### CODE REVIEW

**Comment by InfraredAces** [comment]
I've flashed my Waveshare board with [this build](https://github.com/OpenStickCommunity/GP2040-CE/actions/runs/5717819255) and set the appropriate data pins so that the Keyboard Host Addon is working with a keyboard plugged into the host port.

The action buttons were fixed so that the labels match the proper input. However, with the function buttons A2 and S1 are reversed and require assignments for the other to work properly.

## Example:
### Desired Inputs and Intended Mapping
- A2 - 2
- S1 - 4

### Necessary mapping to get above
- A2 - 4
- S1 - 2

**Comment by deeebug** [comment]
This is a different issue unrelated to the Keyboard Host addon. The labels get swapped incorrectly. I've pushed fixes for these.

**Comment by InfraredAces** [comment]
This does resolve the issues I was having initially with the PR

**Review by arntsonl — APPROVED** [review]
Re-enables keyboard host add-on, looks good!

**Pull request merged**
