### PR TITLE
Cmake Changes, including Docs

### PR DESCRIPTION
**Pull request by Fortinbra**

### CODE REVIEW

**Comment by TheTrainGoes** [comment]
Tested on my M1 Mac.  After some tinkering I got it to work.

```PICO_SDK_FETCH_FROM_GIT=true GP2040_BOARDCONFIG=Pico cmake -B ./build -DCMAKE_BUILD_TYPE=Release

GP2040_BOARDCONFIG=Pico cmake --build ./build --config Release --parallel `sysctl -n hw.ncpu` ```

**Review by TheTrainGoes — DISMISSED** [review]
Working for me.  Also lets me access web-config via Mac.

**Review by arntsonl — APPROVED** [review]
Cmake changes are good, confirmed compiles in Windows.

**Comment by SuperPrower** [comment]
Hi, can confirm. Compiles on Linux, web interface works. It's a bit wonky, I had to manually connect to the network and it disconnected me from my main network (prob NetworkManager's issue), but it works.

**Pull request merged**
