### PR TITLE
web settings  : show button label according to current button  lable type

### PR DESCRIPTION
**Pull request by hitsmaxft**
while setup fn hotkeys on page Settings  ,  i found it hard to setup hotkeys,  cause not familiar with gp2040 button label names

here minor changes in  jsx to  show button label   by   current  button label type ( ps4 , gp2040,  etc..)type

before

图片

after 

图片

change 1:  setting page,  hotkeys  show  buttons  by  current button label type
change 2:  configuration>>pin mapping page,  show function pin input   in pin page , for button label type is ps4

### CODE REVIEW

**Comment by InfraredAces** [comment]
Are you able to provide before/after images to illustrate the change that you made?

**Comment by hitsmaxft** [comment]
> Are you able to provide before/after images to illustrate the change that you made?

image added

**Comment by InfraredAces** [comment]
This PR does not seem to take into account the `Switch Touchpad and Share` with regard to the change of labels based on the Label Selector. 

The GP2040-CE labels for the inputs are static independent of the PS4 labels as outputs to the PC/console  (i.e. `A2` can be `TP` or `Share` depending on the state of this toggle). However, when the toggle is enabled, the physical button used for the shortcut remains unchanged even when the button registers to the PC/console has changed.

Because of this, the team feels it better to have the Hotkey shortcut input labels take into account the `Switch Touchpad and Share` toggle and swap the labels accordingly.

## `Switch Touchpad and Share` Disabled

PS4 Labels
image

GP2040-CE Labels
image


## `Switch Touchpad and Share` Enabled

PS4 Labels
image

GP2040-CE Labels
image

**Comment by hitsmaxft** [comment]
> This PR does not seem to take into account the `Switch Touchpad and Share` with regard to the change of labels based on the Label Selector. 
> 
> 
> 
> The GP2040-CE labels for the inputs are static independent of the PS4 labels as outputs to the PC/console  (i.e. `A2` can be `TP` or `Share` depending on the state of this toggle). However, when the toggle is enabled, the physical button used for the shortcut remains unchanged even when the button registers to the PC/console has changed.
> 
> 
> 
> Because of this, the team feels it better to have the Hotkey shortcut input labels take into account the `Switch Touchpad and Share` toggle and swap the labels accordingly.
> 
> 
> 
> ## `Switch Touchpad and Share` Disabled
> 
> 
> 
> PS4 Labels
> 
> image
> 
> 
> 
> GP2040-CE Labels
> 
> image
> 
> 
> 
> 
> 
> ## `Switch Touchpad and Share` Enabled
> 
> 
> 
> PS4 Labels
> 
> image
> 
> 
> 
> GP2040-CE Labels
> 
> image
> 
> 
> 
> 
Your explanation is very detailed。
I will fix this in a few days.

**Comment by hitsmaxft** [comment]
latest commit fixed "Switch Touchpad and Share" issue

 unchecked

图片

图片

 checked

图片
图片

**Comment by arntsonl** [comment]
Thanks for all of the fixes @hitsmaxft , looks good!

**Review by arntsonl — APPROVED** [review]
Looks good!

**Pull request merged**
