### PR TITLE
allow one GPIO pin to trigger 2+ buttons

### PR DESCRIPTION
**Pull request by bsstephan**
This adds a couple protobuf fields to the `GpioMappingInfo` structure to include dpad and button masks and uses them when setting up the `Gamepad` object to allow a pin to be the trigger for more than one button. All the cost is at setup time, so this shouldn't have any material effect on gamepad performance.

As usual, @Pelsin helped my proto-brain (pun intended) with the UI work. It will need improvement/expansion in the future, but this works for now.

### CODE REVIEW

**Comment by bsstephan** [comment]
This works.

image

via

image

**Comment by arntsonl** [comment]
Is this all ready to review?

**Comment by arntsonl** [comment]
Confirmed this is working, going to have some other eyes on the UI as well.

**Comment by Pelsin** [comment]
> Confirmed this is working, going to have some other eyes on the UI as well.

Thats good! Please ping me if the UI is not good enough for the first iteration, if so i will try to merge the new page with pin mapping page.

**Comment by bsstephan** [comment]
Quick screenshot of the UI as it stands right now in this branch:
image

Note that this can only be done for the time being on the base mappings (profile 1).

**Review by arntsonl — APPROVED** [review]
Looks great! New changes we can put into PRs since this PR is already pretty huge

**Comment by reimertz** [comment]
Thanks for this!

**Pull request merged**
