### PR TITLE
Add forced circularity option and minor fix to analog.cpp

### PR DESCRIPTION
**Pull request by NickGuyver**
Add an analog configuration option to force perfect circularity on analog joystick. This video does a good job of showing why it should be an option - (https://www.youtube.com/watch?v=1P1mItHTKJw)

Nest the deadzone if statements inside the statements where their respective axis is validated.

### CODE REVIEW

**Comment by NickGuyver** [comment]
Adding a couple more things to this PR

Add webconfig option to adjust deadzone for analog joystick
Fix minimum value for adjustable shotcount on webpage to match validated range

**Review by arntsonl — DISMISSED** [review]
This is super neat, thank you for adding this in!

**Comment by arntsonl** [comment]
Looks like we had one merge conflict @NickGuyver , would you mind resolving and I'll get this merged. Thanks!

**Comment by NickGuyver** [comment]
Should be fixed now.

**Review by arntsonl — APPROVED** [review]
Looks good, thanks for fixing that!

**Pull request merged**
