### PR TITLE
Add Stress

### PR DESCRIPTION
**Pull request by Conor-Burns**
This PR adds support for the Stress FightPad

### CODE REVIEW

**Comment by arntsonl** [comment]
Hi Conor, could you please let us know what a Stress board is? None of the team at gp2040-ce are familiar with it?

**Comment by SavageCore** [comment]
@arntsonl 

https://github.com/GroooveBob/Stress

**Comment by arntsonl** [comment]
@Conor-Burns , we're going to merge this one in. Could you update the PR to resolve the conflicts?

**Comment by Conor-Burns** [comment]
@arntsonl will do so tomorrow - thank you :)

**Comment by SavageCore** [comment]
I was getting frustrated redoing the pin config when rebuilding all the time so I did the rebase myself. Currently this is my main test device :)

@Conor-Burns Do you want to take the code and add it to this PR or shall I submit a new one?
https://github.com/SavageCore/GP2040-CE/tree/feature/add-stress

**Comment by arntsonl** [comment]
Going to use PR#316 with our updated code

**Comment by Conor-Burns** [comment]
@SavageCore thank you for taking the time and doing the config❤️

**Pull request closed without merging**
