### PR TITLE
Sidewinder Gamepad support

### PR DESCRIPTION
**Pull request by xouillet**
This MR adds support of original Sidewinder Gamepad via its DA-15 port.

Microsoft Sidewinder Gamepad

The DA-15 5V pins (1, 8, 9 and 15) and GND (4, 5 and 12) can be directly connected to the RP2040 +5V and GND pins.

The DA-15 ports pins 2, 3 and 7 should be mapped on RP2040 GPIOs, and set in the web configurator.

Related WebConfigurator MR: https://github.com/OpenStickCommunity/WebConfigurator/pull/67

### CODE REVIEW

**Comment by Fortinbra** [comment]
Does this allow remapping the buttons themselves, or only the pins on the connector?

**Comment by xouillet** [comment]
The mapping is coded in `src/addons/sidewindergp.cpp`, the web configurator only allow pins configuration.

**Comment by arntsonl** [comment]
Also you'll have to pull your WebConfigurator changes into www after merging main in. We got rid of WebConfigurator in favor of www commits going directly to the PR. This makes it WAY less confusing, sorry about the inconvenient timing!

**Comment by xouillet** [comment]
> Do you have any instructions, schematics, or boards we can buy to test this support?

Instructions are described in the MR description and the documentation, basically you have to connect +5V, GND and 3 pins of DB-15 to RP2040 GPIOs.

**Comment by xouillet** [comment]
> Also you'll have to pull your WebConfigurator changes into www after merging main in. We got rid of WebConfigurator in favor of www commits going directly to the PR. This makes it WAY less confusing, sorry about the inconvenient timing!

Done

**Comment by TheTrainGoes** [comment]
Hi @xouillet ,

Do you have schematics for the DB-15 to RP2040 or anything that others can use to build this?  

We are generally reluctant to merge things that none of us have and therefor cannot maintain or test releases on.

**Comment by arntsonl** [comment]
None of the devs on this project have a Sidewinder or a board that can connect DA-15 to RP2040. Going forward, we will want to make sure that all PR submissions to main can be tested by one of the main devs on the team.

**Comment by RobertDaleSmith** [comment]
I don't have the bandwidth at the moment but in the future I would like to circle back to this as I want to create a bunch of controller adapters.. including a DB-15 gamepad adapter to USB. 

@xouillet Can the sidwinder be powered by 3.3v and in return communicate in 3.3v for the gpio pins to be within operating range without level shifters? Either way it shouldn't be too hard to make a board like the one I did for the SNESpad addon.

-> https://www.flux.ai/robertdalesmith/snes-controller-arduino-nano-shield

**Comment by xouillet** [comment]
The sidewinder needs to be powered by +5V, as this is standard DA-15 gameport mapping (cf. https://en.wikipedia.org/wiki/Game_port). However, GPIO communication can happen in 3.3V, so no level shifter are required.

I've made myself a very simple adapter with only a female DA-15 and a Waveshare RP2040 Zero and no other components with the mapping described both in this MR and in the documentation file of the PR. I could draw a schematic for this but it will be dead simple.

Anyway, I may continue rebasing this patch on my fork for my personal use as this PR is refused...

**Comment by clach04** [comment]
Salut @xouillet, Thanks for sharing you PR! I do not have a gamepad but I do have an old analog joystick with a gameport connector. Is it realistic to adapt to analog or is the 3V versus 5V likely to be an issue?

**Pull request closed without merging**
