### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by henrebotha**
This is the result of running `npm audit fix --force`.

### CODE REVIEW

**Comment by Pelsin** [comment]
This does not only update the affected dependencies(nodemon) but also reruns an install ignoring earlier package-lock.json. Re-installing all dependencies according to package.json.

Thats why it update all packages, e.g "vite" in package-lock.json to 4.3.9 -> 4.5.3, which is fine as long as we are aware and have tested these updates.

**Comment by henrebotha** [comment]
Ah good call, I'll see if there's a way to make it respect the lockfile.

**Comment by arntsonl** [comment]
I'm going to set this back to draft until we can verify all the vite changes are valid.

**Comment by arntsonl** [comment]
Yeah I'm going to close this one up. We can do a bigger push to get versions updated, nodemon is not critical right now.

**Pull request closed without merging**
