### PR TITLE
Added Korean localization for new localization labels.

### PR DESCRIPTION
**Pull request by Tomuri32**
I wanted the GP2040-CE Web Configurator in Korean

### CODE REVIEW

**Review by Tomuri32 — COMMENTED** [review]
change wiiaddon.jax file

**Comment by Pelsin** [comment]
Wow so nice to see korean being added <3!
If there are strings that don't need translating/should be kept with the original string, please remove them from the  ko-kr locale and it will fallback to the english(default) one.

**Comment by Tomuri32** [comment]
> Wow so nice to see korean being added <3! If there are strings that don't need translating/should be kept with the original string, please remove them from the ko-kr locale and it will fallback to the english(default) one.

thanks! :)

**Comment by mizma** [comment]
Nice to see new locales being added!
https://github.com/OpenStickCommunity/GP2040-CE/pull/1048/files this commit log might help in figuring out how to get the new language appear in the final web config build.

- www/src/Components/LanguageSelector.jsx
    - add the locale in language selector so the language can be changed.
    - add link to the country flag icon
- need to add www/src/Icons/Flags/koKR.tsx
    - you'll need to get the flag svg data from https://flagicons.lipis.dev/
- www/src/i18n.jsx
    - add the locale to i18next so the new language is loaded
- www/src/Locales/**/Components.jsx
    - need to add the translation of the language name in language selector.

**Comment by Tomuri32** [comment]
> Nice to see new locales being added! https://github.com/OpenStickCommunity/GP2040-CE/pull/1048/files this commit log might help in figuring out how to get the new language appear in the final web config build.
> 
> * www/src/Components/LanguageSelector.jsx
>   
>   * add the locale in language selector so the language can be changed.
>   * add link to the country flag icon
> * need to add www/src/Icons/Flags/koKR.tsx
>   
>   * you'll need to get the flag svg data from https://flagicons.lipis.dev/
> * www/src/i18n.jsx
>   
>   * add the locale to i18next so the new language is loaded
> * www/src/Locales/**/Components.jsx
>   
>   * need to add the translation of the language name in language selector.

I have completed everything you informed me about. Thank you!

**Comment by arntsonl** [comment]
This is super cool!! We're are going to hold off on merging this for 0.7.11 as we have so many changes going into 0.7.10. I'll be approving and merging this after we get 0.7.10 release. Thank you for the PR!

**Comment by Tomuri32** [comment]
> This is super cool!! We're are going to hold off on merging this for 0.7.11 as we have so many changes going into 0.7.10. I'll be approving and merging this after we get 0.7.10 release. Thank you for the PR!

update  ko-KR/Addons/WiiAddon.js

**Comment by Tomuri32** [comment]
[/ko-KR/Navigation.jsx] Delete the duplicate key.
[/ko_KR/LayoutConfig.jsx]I have fixed the missing '.

**Comment by arntsonl** [comment]
Would you like a little bit of time to fix anything? Or is this ready to merge?

**Review by arntsonl — APPROVED** [review]

**Comment by arntsonl** [comment]
Looks great! Any changes to this you can do as an additional PR, thanks for the contributions!!

**Pull request merged**
