### PR TITLE
Implement Focus Mode addon

### LINKED ISSUE #268: Bounty - Aux button lockout add-on.
While I realize a physical switch might work better, if possible I would like to ask for an add on that when pressed effectively renders the menu buttons as non functional, until the 'lock' button gets pressed again.

### PR DESCRIPTION
**Pull request by deeebug**
Resolves #268.

This is a new addon that lets given inputs to be negated while the specified pin is held. Currently, arbitrary buttons can be set via the web-config.

### CODE REVIEW

**Review by arntsonl — APPROVED** [review]
Looks clean!

**Comment by arntsonl** [comment]
Requesting a re-open when more features have been added via @TheTrainGoes and @deeebug

**Comment by deeebug** [comment]
The button lock addon is now Focus Mode.
In addition to buttons, it also supports locking the OLED display and RGB LED.

Also, migrated to ProtoBuf.

**Review by arntsonl — APPROVED** [review]
Looks good!

**Pull request merged**
