### PR TITLE
Update OpenCore0 pictures from WASD to base unit.

### PR DESCRIPTION
**Pull request by MajorArkwolf**
The OpenCore0 README references two images (Open_Core0.JPG and Open_Core0_pinout.png) that are not present in the current directory. Instead, the images in the assets folder are for the WASD variant. 

This PR removes the incorrect WASD pictures and adds the correct OpenCore0 variant images so the readme points to the correct images.

For the pinout, I opted to refer to the action buttons by the P & K as per the request of TheTrain and to match the existing WASD board pinout

### CODE REVIEW

**Comment by mikepparks** [comment]
Please be mindful in the terminology used. This is a leverless or all button variant.

**Comment by TheTrainGoes** [comment]
I have manually removed the offending words.

**Comment by MajorArkwolf** [comment]
@TheTrainGoes still able to review this one?

**Comment by TheTrainGoes** [comment]
Hey @MajorArkwolf ,

This is pretty low priority as we get v0.7.7 rolling out.  

I will look into it more when I have a bit of time.

**Comment by TheTrainGoes** [comment]
I have addressed this in https://github.com/OpenStickCommunity/GP2040-CE/pull/815 based off of the original images.

I have also added a GPIO mapping image and an RGB LED order image.

Closing this PR.

**Pull request closed without merging**
